// gen-samples.ts — bundle the repository samples/ tree into src/samples.gen.ts.
//
// The embeddable web IDE has no server, so the read-only sample files are baked
// into the bundle as a { path: content } map. User edits live in LocalStorage
// (see webfs.ts). Run before dev/build (see the app's package scripts).
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const SAMPLES = join(import.meta.dir, "../../../../samples");
const OUT = join(import.meta.dir, "../src/samples.gen.ts");
const EXTS = [".gad", ".gadt", ".giom"];

function walk(dir: string, acc: string[]): string[] {
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (EXTS.some((e) => name.endsWith(e))) acc.push(p);
  }
  return acc;
}

const files = walk(SAMPLES, []);
const entries = files
  .map(
    (p) =>
      `  ${JSON.stringify(relative(SAMPLES, p).split(sep).join("/"))}: ${JSON.stringify(readFileSync(p, "utf8"))},`,
  )
  .join("\n");

writeFileSync(
  OUT,
  `// Generated by scripts/gen-samples.ts. DO NOT EDIT.\n` +
    `// Read-only sample tree bundled for the embeddable web IDE.\n` +
    `export const samples: Record<string, string> = {\n${entries}\n};\n`,
);

console.log(`samples.gen.ts: ${files.length} files`);
